socialMedia/FlaskProject/posts/routes.py
from flask import render_template, request, redirect, flash, request, url_for, abort, Blueprint
from FlaskProject.posts.form import  PostForm
from FlaskProject.models import  Post, User
from flask_login import current_user, login_required
from FlaskProject import db
from datetime import datetime

posts = Blueprint('posts', __name__)

@posts.route('/post/new', methods=['GET','POST'])
@login_required
def create_post():
    form = PostForm()
    if form.validate_on_submit():
        post = Post(title=form.title.data, content=form.content.data, author_id=current_user.id)
        db.session.add(post)
        db.session.commit()
        flash('Create a post successfully!!')
        return redirect('/')
    return render_template('createPost.html', form=form)
@posts.route('/post/<int:post_id>', methods=['GET'])
@login_required
def post(post_id):
    post = Post.query.get(post_id)
    return render_template('post.html', title='Post', post=post)
@posts.route('/post/<int:post_id>/update', methods=['GET', 'POST'])
@login_required
def update_post(post_id):
    post = Post.query.get(post_id)
    if current_user.username != post.author.username:
        abort(403)
    form = PostForm()
    if form.validate_on_submit():
        post.title = form.title.data
        post.content = form.content.data
        post.date = datetime.now()
        db.session.commit()
        flash('Update post successfully!!')
        return redirect(f'/post/{post_id}')
    form.title.data = post.title
    form.content.data = post.content
    return render_template('createPost.html',title='Update Post' , form=form)
@posts.route('/post/<int:post_id>/delete', methods=['GET', 'POST'])
@login_required
def delete_post(post_id):
    post = Post.query.get(post_id)
    if current_user.username != post.author.username:
        abort(403)
    db.session.delete(post)
    db.session.commit()
    flash('Delete post successfully!!')
    return redirect('/')

@posts.route('/author/<int:author_id>', methods=['GET'])
@login_required
def author(author_id):
    posts = User.query.order_by(Post.date.desc()).get(author_id).posts
    return render_template('home.html', posts = posts)

socialMedia/FlaskProject/users/routes.py
from flask import render_template, request, redirect, flash, request, url_for, Blueprint, current_app
from FlaskProject.users.form import RegisterForm, LoginForm, UpdateForm, ResetPasswordForm, ResetRequestForm
from FlaskProject import mail, db, bcrypt
from FlaskProject.models import User
from flask_login import login_user, current_user, logout_user, login_required
from flask_mail import Message
from FlaskProject.users.utils import saveImage, send_reset_email, verify_token

users = Blueprint('users', __name__)

@users.route('/register', methods=['GET','POST'])
def register():
    if current_user.is_authenticated:
        return redirect('/')
    form = RegisterForm()
    if form.validate_on_submit():
        data = User.query.filter_by(username=form.username.data).first()
        if data == None:
            hashpw = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
            user = User(username=form.username.data, passwd=hashpw, email=form.email.data)
            db.session.add(user)
            db.session.commit()
            flash(f'Account {form.username.data} is created successfully')
            return redirect('/login')
        else:
            form.username.errors.append("Username has already existed !")
            return render_template('register.html', form=form)
    else:
        return render_template('register.html', form=form)

@users.route('/login', methods=['GET','POST'])
def login():
    if current_user.is_authenticated:
        return redirect('/')
    form = LoginForm()
    if form.validate_on_submit():
        data = User.query.filter_by(username=form.username.data).first()
        if data != None: 
            if bcrypt.check_password_hash(data.passwd, form.password.data):
                flash('Login successfully!!')
                login_user(data, remember=False)
                next_page = request.args.get('next')
                if next_page:
                    return redirect(next_page)
                else:
                    return redirect('/')
            else:
                form.password.errors.append('Wrong password')
        else:
            form.username.errors.append('Username does not exists')
        
    return render_template('login.html', form=form)

@users.route('/logout')
def logout():
    logout_user()
    flash('Logout successfully !!!')
    return redirect('/')


@users.route('/content', methods=['GET','POST'])
@login_required
def content():
    form = UpdateForm()
    if form.validate_on_submit():
        data1 = User.query.filter_by(username=form.username.data).first()
        data2 = User.query.filter_by(email=form.email.data).first()
        if data1== None or data1.username == current_user.username  :
            if  data2== None or data2.email == current_user.email  :
                current_user.username = form.username.data
                current_user.email= form.email.data
                if form.picture.data:
                    picture_name =  saveImage(form.picture.data)
                    current_user.picture = picture_name
                db.session.commit()
                flash("Update successfully !!")
            else:
                form.email.errors.append('Username already existed')
        else:
            form.username.errors.append('Username already existed')
        return redirect('/content')
    form.username.data = current_user.username
    form.email.data= current_user.email
    return render_template('content.html', title='Profile', form=form)

@users.route('/reset_password', methods=['GET', 'POST'])
def send_request():
    if current_user.is_authenticated:
        return redirect('/')
    form = ResetRequestForm()
    if form.validate_on_submit():
        data = User.query.filter_by(email=form.email.data).first()
        if data:
            send_reset_email(data)
            flash('The request has been sent. Please check your email')
        else:
            form.email.errors.append('Email does not exist in database')
    return render_template('reset_request.html', form=form)

@users.route('/reset_password/<token>', methods=['GET', 'POST'])
def reset_password(token):
    if current_user.is_authenticated:
        return redirect('/')
    name =  verify_token(token)
    if name is None:
        flash('Invalid token or token has expired')
        return redirect('/reset_password')
    else:
        form = ResetPasswordForm()
        if form.validate_on_submit():
            data = User.query.filter_by(username=name).first()
            hashpw = bcrypt.generate_password_hash(form.password.data)
            data.passwd = hashpw
            db.session.commit()
            flash('Reset password successfully !')
            return redirect('/login')
    return render_template('reset_password.html', form = form)

socialMedia/FlaskProject/templates/content.html
{% extends "layout.html" %}

{% block body %}
<main class="content">
    <h1>Profile</h1>
    <img src="{{ url_for('static', filename=current_user.picture )}}" , style="width:150px;height:150px;border-radius: 100%;"><br>

    <form action="" method= 'POST' enctype="multipart/form-data">
        {{form.hidden_tag()}}
        <div class="update-input">
            {{form.username.label}}<br>
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}
            {{form.username(class="update-input-form")}}
        </div>
        <div class="update-input">
            {{form.email.label}}<br>
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}
            {{form.email(class="update-input-form")}}
        </div>
        <div class="update-input">
            {{form.picture.label()}}<br>
            {{form.picture}}<br>
            {% if form.picture.errors %}
                {% for error in form.picture.errors %}
                <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}<br>
            
        </div>
        <div>
            {{form.submit(class="submit")}}
        </div>
    </form>
</main>
{% endblock body %}

socialMedia/FlaskProject/templates/createPost.html
{% extends "layout.html" %}
{% block body %}
<form action="" method="POST" class="form">
    {{form.hidden_tag()}}
    <div class="input">
        {{form.title.label}}<br>
        {% if form.title.errors %}
            {% for error in form.title.errors %}
            <span class="error">{{error}}</span><br>
            {%endfor%}
        {% endif %}
        {{form.title(class="input-form")}}
    </div>
    <div class="input">
        {{form.content.label}}<br>
        {% if form.content.errors %}
            {% for error in form.content.errors %}
            <span class="error">{{error}}</span><br>
            {%endfor%}
        {% endif %}
        {{form.content(class="input-form")}}
    </div>
    <div >
        {{form.submit(class="submit")}}
    </div>
</form>
{% endblock body%}

socialMedia/FlaskProject/templates/home.html
{% extends "layout.html" %}

{% block body %}
    <main class="home-posts">
    {% if current_user.is_authenticated %}
        {% if posts %}
            {% for post in posts %}
            <article class="post">
                <div class="header-post"> 
                    <a class="user-link" href="{{url_for('posts.author',author_id= post.author_id)}}">{{post.author.username}}</a>
                    {{post.date}}
                </div>
                <div> 
                    <a class="post-link" href="{{url_for('posts.post', post_id=post.id)}}"><h3 style="display:inline;">{{post.title}}</h3></a>
                </div>
                <div>
                    <p>{{post.content}}</p>
                </div >
            </article>
            {% endfor %}
        {% endif %}
    {% endif %}
    </main>
{% endblock body %}

socialMedia/FlaskProject/templates/layout.html
<html>
    <header>
        {% if title %}
            <title>{{title}}</title>
        {% else %}
            <title>Default title</title>
        {% endif%}
        <style>
            @import url('https://fonts.googleapis.com/css?family=Libre+Baskerville&display=swap');
            @import url('https://fonts.googleapis.com/css?family=Barlow:600|Libre+Baskerville&display=swap');
            @import url('https://fonts.googleapis.com/css?family=Permanent+Marker&display=swap');
            @import url('https://fonts.googleapis.com/css?family=Caveat&display=swap');
            @import url('https://fonts.googleapis.com/css?family=Nunito+Sans&display=swap');
            
            .body-layout{
                margin:0;
                background-image: url(/static/background.jpg);
                background-position: center;
            }
            .login-page{
             border: 1px solid #000;
            }
            .side-bar{
                display: flex;
                flex-direction: row;
                justify-content: space-evenly;
                align-items: center;
                position: absolute;
                top:0;
                left: 50%;
                transform: translate(-50%,0%);
                height:8%;
                min-width: 80%;
                background: rgba(0,0,0, 0.5);
                
            }
            .link{
                font-family: 'Libre Baskerville', serif;
                font-size: 25px;
                font-weight: bold;
                text-decoration: none;
                color:white;
            }
            .form{
                position: absolute;
                text-align: center;
                top: 50%;
                left: 50%;
                transform: translate(-50%, -50%);
                min-width: 30%;
                height: auto;
                background: rgba(0, 0, 0, 0.4);
                padding: 20px;
                color: white;
                border-radius: 30px;
            }
            .form h1{
                font-family: 'Permanent Marker', cursive;
                font-size: 50px;
                font-style: italic;
                margin:0;
            }
            .input{
                text-align: left;
                padding: 10px 0;
                font-size: 20px;
                font-family: 'Barlow', sans-serif;
                font-style: italic;

            }
            .input-form{
                width:100%;
                background: none;
                border: none;
                border-bottom: 1px solid #2ecc71;
                outline:none;
                color:white;
                font-size: 17px;
                margin: 5px;
                padding: 5px;
                text-align: center;
            }
            .submit{
                border: none;
                outline: none;
                font-family: 'Permanent Marker', cursive;
                text-align: center;
                font-size: 40px;
                color: white;
                width:auto;
                height:15%;
                background: linear-gradient(120deg, #9b59b6,#3498db,#8e44ad);
                border-radius: 50px;
                margin: 10px;
                padding: 10px 15px;
                cursor:pointer;
            }
            .link-reset{
                font-family: 'Caveat', cursive;
                text-decoration: none;
                font-size: 20px;
                color: white;
            }
            .home-posts{
                position:absolute;
                top: 13%;
                left: 50%;
                transform: translate(-50%, 0);
                width:80%;
                height: 90%;
                background: rgba(255,255,255, 0.9);
                overflow: scroll;
                overflow-x: hidden;
            }
            .post{
                margin: 10px;
                padding: 10px;
                border-bottom: 1px solid #3498db;
            }
            .header-post{
                display: flex;
                flex-direction: row;
                justify-content: space-between;
            }
            .user-link{
                text-decoration: none;
                color: #3498db;
            }
            .post-link{
                text-decoration: none;
                color: black;
                font-size: 20px;
            }
            .content{
                position:absolute;
                top: 15%;
                left: 50%;
                transform: translate(-50%, 0);
                width:30%;
                height: 85%;
                text-align: center;
                background: rgba(255,255,255, 0.9);
                overflow: hidden;
                border-radius: 40px;
                padding: 30px 0;
                color: black;
            }
            .content h1{
                font-family: 'Permanent Marker', cursive;
                font-size: 50px;
                font-style: italic;
                margin:0;
            }
            .update-input{
                text-align: left;
                padding: 10px 30px;
                font-size: 20px;
                font-family: 'Barlow', sans-serif;
                font-style: italic;
            }
            .update-input-form{
                width:100%;
                background: none;
                border: none;
                border-bottom: 1px solid #2ecc71;
                outline:none;
                color:black;
                font-size: 17px;
                margin: 5px;
                padding: 5px;
                text-align: center;
            }
            #picture{
                margin: 10px 0;
                font-size:15px;
            }
            .user-post{
                position:absolute;
                top: 15%;
                left: 50%;
                transform: translate(-50%, 0);
                width:40%;
                height:auto;
                background: rgba(255,255,255, 0.9);
                border-radius: 40px;
                padding: 30px 30px;
                color: black;
            }
            .edit-post{
                text-decoration: none;
                outline: none;
                background: linear-gradient(150deg, #3498db ,#9b59b6);
                padding:10px;
                margin: 20px 10px;
                border-radius: 20px;
                color:white;
            }
            .error{

                font-family: 'Nunito Sans', sans-serif;
                font-size:17;
                font-style: normal;
                color:#e74c3c;
            }
            .flash{
                position: absolute;
                top: 8%;
                left:50%;
                transform:translate(-50%,0);
                padding: 5px;
                width: 80%;
                height: auto;
                border: 1px solid #27ae60;
                border-radius: 20px;
                background: rgba(39, 174, 96, 0.3);
                text-align: center;
                color: #27ae60;
            }
        </style>
    </header>
    <body class="body-layout">
        {% with messages = get_flashed_messages() %}
            {% if messages %}
                {% for message in messages %}
                <div class="flash">
                    {{message}}
                </div>
                {% endfor %}
            {% endif %}
        {% endwith %}
        <header class='side-bar'>
        {% if current_user.is_authenticated %}
            <a class="link" href="/logout">Log out</a>
        {% else %}
            <a class="link" href="/register">Register</a>
            <a class="link" href="/login">Login</a>
        {% endif %}
            <a class="link" href="/content">Content</a>
            <a class="link" href="/post/new">Post</a>
            <a class="link" href="/">Home</a>
        </header>

        {% block body %} 
        {% endblock body %}
    </body>
</html>

socialMedia/FlaskProject/templates/login.html
{% extends "layout.html" %}
{% block body %}

<form action="" method="POST" class="form" >
    {{form.hidden_tag()}}
    <h1>Login</h1>
    <div class="input">
        {{form.username.label}}<br>
        {% if form.username.errors %}
            {% for error in form.username.errors %}
            <span class="error">{{error}}</span><br>
            {%endfor%}
        {% endif %}
        {{form.username(class="input-form")}}
    </div>
    <div class="input">
        {{form.password.label}}<br>
        {% if form.password.errors %}
            {% for error in form.password.errors %}
            <span class="error">{{error}}</span><br>
            {%endfor%}
        {% endif %}
        {{form.password(class="input-form")}}
    </div>
    <div>
        {{form.submit(class="submit")}}
    </div>
    <a class="link-reset" href="{{url_for('users.send_request')}}">Forgot Password?</a>
</form>
{% endblock body %}

socialMedia/FlaskProject/templates/post.html
{% extends "layout.html" %}

{% block body %}
<br><br>
<main class="user-post">
    {% if current_user.is_authenticated %}
        {% if post %}
            <article >
                <div class="header-post"> 
                    <a class="user-link" href="{{url_for('posts.author',author_id = post.author_id)}}">{{post.author.username}}</a>
                    {{post.date}}
                </div>
                <div> 
                    <h3 >{{post.title}}</h3>
                </div>
                <div>
                    <p>{{post.content}}</p>
                </div >
                <a class="edit-post" href="{{url_for('posts.update_post', post_id = post.id)}}">Update</a>
                <a class="edit-post" href="{{url_for('posts.delete_post', post_id = post.id)}}">Delete</a>
            </article>
        {% endif %}
    {% endif %}
</main>
{% endblock body %}

socialMedia/FlaskProject/templates/register.html
{% extends "layout.html" %}
{% block body %}
    <form action="" method="POST" class="form">
        {{form.hidden_tag()}}
        <h1>Register</h1>
        <div class="input">
            {{form.username.label}}<br>
            {% if form.username.errors %}
                {% for error in form.username.errors %}
                    <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}
            {{form.username(class="input-form")}}
        </div>
        <div class="input">
            {{form.email.label}}<br>
            {% if form.email.errors %}
                {% for error in form.email.errors %}
                    <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}
            {{form.email(class="input-form")}}
        </div>
        <div class="input">
            {{form.password.label}}<br>
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}
            {{form.password(class="input-form")}}
        </div>
        <div class="input">
            {{form.confirm.label}}<br>
            {% if form.confirm.errors %}
                    {% for error in form.confirm.errors %}
                        <span class="error">{{error}}</span><br>
                    {%endfor%}
            {% endif %}
            {{form.confirm(class="input-form")}}
        </div>
        <div>
            {{form.submit(class="submit")}}
        </div>
    </form>
{% endblock body %}

socialMedia/FlaskProject/templates/reset_password.html
{% extends "layout.html" %}
{% block body %}
    <form action="" method="POST" class="form">
        <h1>Reset Password</h1>
        {{form.hidden_tag()}}
        <div class="input">
            {{form.password.label}}<br>
            {% if form.password.errors %}
                {% for error in form.password.errors %}
                    <span class="error">{{error}}</span><br>
                {%endfor%}
            {% endif %}
            {{form.password(class="input-form")}}
        </div>
        <div class="input">
            {{form.confirm.label}}<br>
            {% if form.confirm.errors %}
                    {% for error in form.confirm.errors %}
                        <span class="error">{{error}}</span><br>
                    {%endfor%}
            {% endif %}
            {{form.confirm(class="input-form")}}
        </div>
        <div>
            {{form.submit(class="submit")}}
        </div>
    </form>
{% endblock body %}

socialMedia/FlaskProject/templates/reset_request.html
{% extends "layout.html" %}
{% block body %}

<form action="" method="POST" class="form">
    <h1>Email To Reset Password</h1>
    {{form.hidden_tag()}}
    <div>
        {% if form.email.errors %}
            {% for error in form.email.errors %}
            <span class="error">{{error}}</span><br>
            {%endfor%}
        {% endif %}
        {{form.email(class="input-form")}}
    </div>
    <div>
        {{form.submit(class="submit")}}
    </div>
</form>
{% endblock body %}